### ISSUE TITLE
Plugin Ordering

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#102]

**Comment by mariusandra** [comment]
This plugins page is about to get a lot more dynamic. We now have up to two sections in the "installed" tab:

![image](https://user-images.githubusercontent.com/53387/105779914-a76ed800-5f6f-11eb-88ea-ee7b576b1a72.png)

To do ordering, we can split the "installed plugins" section into two: "enabled plugins" and "installed plugins". The first section would have a way to drag them up and down, like we do with the funnel steps now. The order would also need to be visually emphasized somehow, and obviously when plugins get enabled/disabled, we should move them.

Finally (and out of scope of this issue), I'd also merge the "repository" section under these two and add a search bar.

**Comment by paolodamico** [comment]
Sorry was late to the party on https://github.com/PostHog/posthog/pull/3057, but hope my feedback for this is relevant,

- I've been playing around with a component like this for match groups. One interesting piece of feedback I got is that the numbers clearly convey ordering which is what we want here, so it might be useful. We would obviously need to add some sort of handle to allow re-ordering plugins intuitively.
   ![image](https://user-images.githubusercontent.com/5864173/105812334-41ee0c00-5fae-11eb-83af-4606458c4e78.png)
- In addition to the above, I would probably add an arrow at the end of each card (between each plugin) to further reinforce the idea of sequential ordering.
- Based on the need to separate enabled/disabled plugins, I would now no longer separate _Plugins to update_ and maybe instead just add a banner at the top saying there are updates available for plugins, and adding a clear visual indicator in each plugin card. I think having a third section might be too confusing.
- Thinking out loud here, but maybe I want installed but disabled plugins in the ordering sequence too? This way if I disable one (presumably temporarily otherwise I would uninstall), all the configuration (including ordering) is kept, and I can turn it back on swiftly. Maybe then I would just add a clear indication that the plugin is currently being bypassed (e.g. 50% opacity, removing the arrow from the point above, ...) I also like this idea because it allows us to keep a single section.
- Definitely add a search bar. You don't necessarily need to merge everything in one tab, the idea of tabs is keeping things organized, and if what you intend is to provide "universal search" functionality then I think it's just a matter of when searching you do show results from all three tabs (grouped of course).

Let me know if you want to work on some more specific designs together or I can help in any other way.

**Comment by mariusandra** [comment]
Thanks for the thoughts!

Regarding "Thinking out loud here, but maybe I want installed but disabled plugins in the ordering sequence too?", that might indeed be something users will want. Right now I'd assume each newly enabled plugin will just go to the end of the list and you can then drag it in the right place, but that might be annoying.

An alternative and perhaps a better approach to making two separate lists is to have a "reorder plugins" button, which would just hide all disabled plugins and let you only reorder the enabled ones (until you click "Save order"). Clicking this could even swap out the enable/disable toggle with the "::" (drag me) icon. The "hidden/disabled" plugin would still remain "in place" after ordering, so while all plugins will have an order 1, 2, 3, ... 6, enabled plugins will be for example 1, 2, 5, 6. I hope I'm somewhat clear with this description. I can make a quick demo otherwise.

This hiding functionality might even be needed, as actually not all enabled can be ordered! Plugins have a few things they can do, `processEvent` and `runEveryMinute` are two of them. If the plugin just runs every minute and uses the posthog API to save annotations from Github, reordering it does nothing. These "unorderable yet enabled" plugins could also be hidden then when you start ordering.

One related thought that I had was to improve the display of the plugins and adding tags for the functionality of the plugin. E.g. a tag for `processEvent` and another for `runEveryMinute` or `runEveryHour`, so by looking at it you can get some idea of what the plugin is doing.

Overall, there's still a lot that we can improve here! Though today I'll leave this task as is and switch to getting ingestion as live as possible.

**Comment by paolodamico** [comment]
Great! Will try to use numbered points, lmk if it's not clear.

1. Perfect! Though I do think it makes sense for **freshly** installed plugins to go at the bottom until you re-arrange them. Re-enabled plugins would then keep their ordering location.
2. I think it was clear. Top of mind seems to introduce UX complexity (now I have to think about enabling ordering mode vs just dragging stuff), but I think this is one of those things that until we use it (particularly the option I'm proposing) we'll now if it's a right fit or not.
3. Having read this later, I think separating the ordering mode might make sense. My only concern here is that we clearly show ordering in the default list mode (e.g. via a simple visual diagram). The problem if we don't do this is that ordering might not be very discoverable/understandable.
4. That makes total sense! Perhaps with some cool icons? As we're already using tags to indicate if it's official o community.

**Comment by mariusandra** [comment]
I did a bit of work on this yesterday and didn't push it yet. Changes in https://github.com/PostHog/posthog/pull/3100 .

![2021-01-27 07 54 53](https://user-images.githubusercontent.com/53387/105954549-1c780580-6075-11eb-8482-e9a76d6720c4.gif)

I definitely could use some eyes and commits on making the first part of the "card" better looking more obviously draggable. 

I think we do need an "order mode" and a step before saving them (as it's a complex operation on the plugin server, best to not do it too frequently), but it could be activated by just starting to drag instead of clicking the "Rearrange" button.

It's all very draft :).

**Comment by mariusandra** [comment]
Closed with https://github.com/PostHog/posthog/pull/3100
