### ISSUE TITLE
Move from `plugin.json` to `package.json`

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#13]
Now that you can install plugins from npm, a `package.json` file is required. It duplicates most of the fields from `plugin.json` (`name`, `description`, `main` as is, `url` --> `homepage`), with the exception of `lib` and `config`.

We can just remove `lib` and keep all code in `main` / `index.js`. Most plugins will be compiled down to one `.js` file anyway, and magically including all code in `lib.js` inside `index.js` doesn't lead to a good experience while developing (no autocomplete for functions in lib.js).

For `config`, we can just use [config](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#config) in package.json.

**Comment by mariusandra** [comment]
I want to revert/cancel this issue. I've been very hesitant to merge these changes and when I'm stalling like that it's usually for a reason.

I now sincerely believe adding support for reading plugin information from `package.json` makes the entire experience worse for everyone. Why? Well, I guess at the end of the day it's subjective and I still can't put my finger down on *one specific reason*, but here are some points.

Speaking against package.json (in no specific order):

- We will have 2 ways to support going forward. Two different ways to document and constantly explain to users when to use one or the other. Just in principle that's probably one too many.
- This increases the cognitive barrier of entry to creating plugins.
- The plugin-specific fields just get lost inside `package.json`. There's way too much other stuff. If we would only use NPM for distribution (like vscode), I'd probably be fine with it, but we have many ways to distribute plugins.
- `package.json` is for node packages. Not all plugins are nor want to be node packages. It's fine to just host some JS code on your gitlab private repository and not have to worry about any NPM-specific stuff. Many people already do that!
- I think we should make the `name` field in `plugin.json` less strict and effectively a "display name". Right now it's basically a "unique key", but it shouldn't be. I can see cases where you want to install the same plugin twice (e.g. the github star sync plugin to sync multiple repos). With `package.json`, the name has to be the name of the NPM package. Having an extra `"displayName"` field in `package.json` is not a standard solution and this is again something that needs to be documented, explained, made sure that people follow it, etc.
- If you just host a `index.js` on github (for version control only), I'd definitely suggest using a simple `plugin.json` file and just skip the `package.json`.
- All of this provides a really clean separation of concerns. `package.json` is for your local tooling and for npmjs.com distribution. `plugin.json` is there to describe the plugin structure. There is not that much that will be duplicate between the files. See for example the github star sync repo.
- The `url` field in `plugin.json` and the `homepage` field in `package.json` are not the same. The latter almost always ends with `#readme` for better or worse, but we want the pure repo url... or perhaps even the npmjs url, which you don't put in package.json.
- It increases the complexity of the code in the plugin server and posthog repos.

Speaking for package.json:
- You have everything in one file which helps save some keystrokes when you are using NPM packages

At the end of the day, keeping the plugin config simple and in its own file just makes the experience of writing plugins simpler... and normally in case of competing solutions, the simpler one should win.

@Twixes any thoughts? :D

**Comment by Twixes** [comment]
Well, my points 😄: 
1. Since we're in an "I wish to enable plugins" beta, I'm in favor of removing support from `plugin.json` before we go out of beta – the migration is incredibly straightforward and will save us complexity with handling 2 similar files in the next… years.
2. My feeling was a whole new file with a schema that's uncannily similar to `package.json`, but _not quite_, is more cognitive load.
3. The only PostHog plugins-specific field we add is `configSchema` AFAIK.
4. If it's an installable plugin, it's a package by definition AND it needs that damned `plugin.json` file anyway. Installable plugins can't do without metadata and `package.json` is the standard way of keeping metadata in Node files. And Node will create it for you! `npm init` and you've got a nice package faster than you can copy and edit `plugin.json` from somewhere. As for source code plugins, the GitHub analogy for them is Gists – super basic stuff where you don't even need commit messages. 
5. `displayName` is an elegant and standard solution to this. VS Code extensions use it for example: https://github.com/Twixes/pypi-assistant/blob/master/package.json (overall recommend the VS Code schema, it makes really nice use of `package.json`).
6. Even hosting just `index.js` running `npm init` is a super quick and friendly experience.
7. It's quite standard to use `package.json` for extensions/plugins, mentioned VS Code, here's Atom too: https://github.com/atom/teletype/blob/master/package.json. `package.json` is for describing the package as a whole, not just dependencies and tooling.
8. Agree that `homepage` doesn't quite fit our needs. Though I'm not a fan of `url` either, it's very vague… How about `sourceUrl`?
9. Again, we're still in a position where we can make a breaking change here or there (with some notice beforehand). And in the end it'll be simpler for both us and plugin-writers to use the standard `package.json`. So IMO we should set on that.

**Comment by yakkomajuri** [comment]
I definitely like the separation of concerns here, even if there are some overlapping fields.

**Comment by mariusandra** [comment]
Not too much participation in slack and here, but the current tally is 3 votes for plugin.json and 1 vote for package.json.

I could find and reply with a counter to most of your 9 points, but I don't think that will move the needle one way or another. 

Thus I'll just say that `package.json` is something that's only found in the NPM ecosystem (vscode distributes its plugins through npm). There are alternative JS/TS implementations (e.g. Deno) that totally don't use it, and if we push towards it, we will be limiting the doors we can open in the future.

For example, we might even implement our own package/plugin repository, as hinted to in this issue: https://github.com/PostHog/posthog/issues/2955 . If we do so, relying on package.json doesn't make sense. 

However, most of all, it's the complexity that's introduced with `package.json`. We will need users to provide a ecosystem-unique `name` for the package, which we just don't need internally. We will need users to know to fill in the relevant fields inside all the unneccesary (for us) fields that `npm init` adds. For new developers the separation of concerns makes a big difference. If you clone an existing plugin (as many users will no doubt do), they won't know what is important in package.json and what's not. If everything is just inside a plugin.json, it's self evident.

Dunno. There are many things I could still add, and I really wish to reach a consensus and not either pull seniority nor push for something that leaves a bad feeling in anyone's mouth, but I really want to move on.

**Comment by Twixes** [comment]
Alright. _IMHO_ not the ideal solution, but it's fine too and I definitely don't want to stall a project over such minutiae. `plugin.json` it is.
