### ISSUE TITLE
Kafka producer is slow

### ISSUE THREAD

**Issue by macobo** [PostHog/plugin-server#264]
Related issue(s): #248, #263

[On our internal plugin server dashboard](https://metrics.posthog.com/d/h_MvYE8Gk/plugin-server-internal-metrics) we can see that our kafka producer is quite slow (p99 being 300-400ms per message):

![image](https://user-images.githubusercontent.com/148820/111769859-5d8cd900-88b2-11eb-9786-a62bdc323ee8.png)

Before implementing the average times were not much better and the producer was taking up the majority of time in ingestion:

![image](https://user-images.githubusercontent.com/148820/111770038-962cb280-88b2-11eb-8eb7-a3539477a2cc.png)

This is not common - e.g. our python producers are much faster. We should figure out a solution here.

cc @fuziontech

**Comment by macobo** [comment]
Small update on this. After https://github.com/PostHog/posthog/issues/3632 we had the number of events go down significantly while processing time went up - due to the kafka producer.

![image](https://user-images.githubusercontent.com/148820/112142688-95ac5880-8bdf-11eb-92e5-4572fa099e3a.png)

On the python end of things things got faster even with the larger messages and extra compressions!

**Comment by macobo** [comment]
Not a major issue right now with everything else being relatively streamlined. Can wait a bit. :)

**Comment by mariusandra** [comment]
Based on what I've observed, when Kafka producer gets slow, it's either a) (unlikely) some weird network or kafka issue, or b) (likely) the plugin server is actually very busy and the `await producer.produce({...})` just doesn't resolve because there are too many other unresolved promises jamming the JS event bus, but the single threaded event loop is stuck behind something sync and stupid, like [running `getPiscinaStats` 3x per event](https://github.com/PostHog/plugin-server/pull/347).

That case resulted in the most typical looking "kafka is slow" graph.

In any case, https://github.com/PostHog/plugin-server/pull/346 reorganised Kafka batches and I haven't seen any slowness since.

What's more, in https://github.com/PostHog/plugin-server/issues/348 I'm advocating for moving producing into Kafka into the background, no `awaits`. This background kafka producer should be smart enough to pause ingestion in case it can't produce fast enough. In case of trouble (e.g. kafka really is down, many retries later), it should enter [recovery mode](https://github.com/PostHog/plugin-server/issues/353) and perhaps dump uncommitted messages into a job queue and brace for reboot.

Thus I'm going to close this and track the topic in the referenced issues.
