### ISSUE TITLE
Discussion: API for user property updates via events

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/plugin-server#386]
We originally just had `posthog.people.set`, which would set "magical" properties $set and $set_once on identify events to add properties to the user.

https://github.com/PostHog/plugin-server/pull/205 added support for those in every event, because some plugins needed that to do their work. 

However, following a demo of `$increment` just now, @timgl mentioned how the API seems confusing if those properties are manually passed by the user. While the idea is to have methods to abstract these away, would we maybe want to nest the properties that update person properties under some other property? Would that make things more clear?

It may also be that it's just a matter of docs. The demo might've looked confusing but realistically one will only find out about that property by reading the docs, so as long as those are good we should be fine? (these don't currently exist though, but they will soon)

Discuss or dismiss :grinning:

**Comment by neilkakkar** [comment]
When you say `posthog.people.set`, I imagine you're talking specifically about the `posthog-js` API?

This is already different from other libraries (ex: `posthog-python` has every type at the top level, since there's no concept of generating "people" on the fly, like in `posthog-js`)

Focusing just on `js`, I think it makes sense to be consistent - if `$set` and `$set_once` happen on `people`, then `$increment` should too. 

And, `$increment` can be a part of properties too, just like set, set_once (? maybe, not sure which direction we want to move in)

**Comment by yakkomajuri** [comment]
Sorry, maybe I was a bit confusing. I'm not talking about the API in the libraries, I'm talking about where those props should be passed inside the `properties` object. Should they stay at the top level or be nested under some `$people` property?

e.g. what is now:

```js
{
    hello: 'world',
    $set: {
        set_this: 1
    }
}
```

To: 
```js
{
    hello: 'world',
    $people: {
        $set: {
            set_this: 1
        }
    }
}
```

**Comment by Twixes** [comment]
I think that since we already support top-level `$set(_once)` _and_ nested under `properties`, we're doing well now and a third option to support wouldn't make things simpler. For HTTP API users we just need clear documentation.
