### ISSUE TITLE
Allow self-hosted users (all users?) to disable plugin logs

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/plugin-server#400]
Depending on the plugins one uses, plugin logs can be quite extensive, making it take up a lot of storage and creates a backlog of slow Postgres insert queries.

Up for debate.

**Comment by Twixes** [comment]
Is this speaking from experience/a user issue?

Maybe the retention of these logs could be configurable instead? Easy for Postgres where retention is a Celery job, trickier for ClickHouse where's it's part of the table schema.

**Comment by mariusandra** [comment]
Indeed, is this premature optimisation or did it come from some user case? 

We should make sure the default repo plugins aren't too noisy... and then it's just up to the self-hosted users to deal with their own logging as they see fit.

**Comment by yakkomajuri** [comment]
Came from local use, which is of course naturally more noisy. My local logs table is already 1/4 of the size of events though, and I keep getting slow query warnings and thus delayed logs. 

Of course local dev is completely different from prod, but made me think

**Comment by mariusandra** [comment]
Is there anything exceptionally noisy there? Or is it just because you restart the server on every code change and that triggers a lot of volume? What kind of MB of data are we looking at? I think probably :thisisfine: and something to work on when a production user has the issue.

Thus, I'll assume we all agree this shouldn't really take any extra dev resources before someone asks for this? I'll close the issue then. :)
