### ISSUE TITLE
Release 1.27.0 1/2

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/plugin-server#453]
Writing up some thoughts prior to the sprint planning tomorrow.

While @mariusandra has moved onto better things :D he has left us with a lot of great context in many places that can help us set priorities.

Here's a list of themes listed in order of priorities from the last planning issue (#402): 

> 1. Data lakes. Exports. Imports. All the data. Reliably. Many different services.
> 2. The deteriorating state of our libraries.
> 3. Keep the lights on work in the plugin server itself.
> 4. New developments that unblock a lot of things: installing plugins, action matching.

As of this week, we now have a new company-wide goal relating to "The Big 5" (see info in [the internal `vpc` repo](https://github.com/PostHog/vpc/issues) about this), so we should be thinking about priorities from this lens. Here are some possible tasks that relate to this goal:

### 1. Data Warehouses

We now have plugins to export events to all of the data warehouses that have been requested to us. They also all have retry queues to ensure data will certainly get sent. So what's next? Here are some ideas (food for thought only):

- Working on also **importing** data from warehouses
- Databricks plugin: https://github.com/PostHog/plugin-repository/issues/25 (requested by a _potential_ user)
- **Exporting people** to warehouses in addition to events
- Metrics on event deliverability: https://github.com/PostHog/plugin-server/issues/452

### 2. Libraries

- Feature Flags on all libraries: https://github.com/PostHog/posthog/issues/1138 - I really think we should start work on this. It's an issue with a lot of upvotes, aligns with our goals very well, and is often requested. We can start with some of the "easy" ones (Node, React Native?), as well as be informed by the [metrics we have on library usage](https://app.posthog.com/dashboard/3102)
- (Try to) Integrate with Snowplow: https://github.com/PostHog/plugin-server/issues/407 (last remaining key CDP)

### 3. Keeping the lights on

- Log queries: https://github.com/PostHog/plugin-server/issues/424 
- Sentry issues need some love

### 4. New developments

- Memory queue: https://github.com/PostHog/plugin-server/issues/421
- Cloud default config fields: https://github.com/PostHog/plugin-server/issues/416
- Read multiple files: https://github.com/PostHog/plugin-server/issues/367
- Plugins frontend: https://github.com/PostHog/plugin-server/issues/413, https://github.com/PostHog/posthog/issues/4557, and https://github.com/PostHog/plugin-server/issues/411
- Faker lib: https://github.com/PostHog/plugin-server/issues/415
- ...and a bunch more issues I won't list here

-----

Having put forward a compilation of things, I'm personally thinking that from a company-wide goals lens, priorities for this sprint should include:

- Feature flags for some select libraries
- Ground work on import plugins **or** people exports 
- Sort out the logs issue: https://github.com/PostHog/plugin-server/issues/424
- Sentry issues (`NaN` one particularly)
( - Finishing up ongoing work e.g. action matching)

cc @Twixes @neilkakkar @timgl

**Comment by Twixes** [comment]
### Quick sprint forecast for the team

- Planned days off: only me on the first Monday
- Support hero duty: none

### Now to planning

V nice writeup @yakkomajuri.

Regarding a few points raised:
1. Feature flags – agreed that there's a need for them. Without a mobile/dedicated SDK dev we don't have the manpower to tackle a ton of them unfortunately… I would definitely suggest Node and React Native as good candidates now too though, they don't need iOS/Android expertise AND see significant usage.
  I'd really like to see a sort of blueprint for feature flags in libraries. What should the right feature flags implementation look like. That would be a bit of a one-off effort, but then every next
2. What do you mean by "`NaN` Sentry issue"?

There's a few tickets I think would be great to tackle (in descending order of effort):
- https://github.com/PostHog/posthog-node/issues/14 Feature flags for Node.
- https://github.com/PostHog/posthog-react-native/issues/25 Feature flags for React Native.
- https://github.com/PostHog/snowflake-export-plugin/issues/3 Snowflake plugin needs to be rearchitected somewhat to reduce costs for its users. I'll take this up since it was Marius and me in touch with Snowflake on this.
- https://github.com/PostHog/plugin-server/issues/411 Should also be simple enough to add polling of plugin configs to show when a plugin errors or is disabled/enabled.
- https://github.com/PostHog/plugin-server/issues/413 It'll now be trivial to show plugin capabilities in the UI.
- https://github.com/PostHog/plugin-server/issues/424 These timeout logs definitely are odd.
- https://github.com/PostHog/plugin-server/issues/410 We could use a small cleanup of internal event data format.

We'd also like to increase organic usage of plugins. Let's think about leaving beta at last.
- https://github.com/PostHog/plugin-server/issues/17 We've been putting off improvements of plugin templates due to more "fundamental" work, but if we want people to take up solving problems with plugins, this is essential.
- https://github.com/PostHog/plugin-server/issues/242 Any last changes to the structure of plugins that we want to make? I think we're in a good spot now actually, so I'd move towards closing this.
- Anything else?

Looking forward to the discussion in planning :) and obvs @timgl's input.

**Comment by yakkomajuri** [comment]
Sentry `NaN` issue: https://sentry.io/organizations/posthog/issues/2225546229/?project=5592816&referrer=slack

<img width="730" alt="Screenshot 2021-06-03 at 10 12 00" src="https://user-images.githubusercontent.com/38760734/120650445-2f03b080-c454-11eb-934d-a5aab871911f.png">

cc @Twixes

**Comment by Twixes** [comment]
Planned!
